workflows:
  compile:
    instance_type: windows_x2
    max_build_duration: 1
    environment:
      groups:
        - choco
    scripts:
      - name: Create target directory
        script: mkdir out

      - name: Pack
        script: choco pack --out out

      - name: Set key
        script: choco apikey --key CHOCO_KEY --source https://push.chocolatey.org/

      - name: Publish
        script: choco push out/dcm.1.2.0.nupkg --source https://push.chocolatey.org/

    artifacts:
      - out/**
