workflows:
  compile:
    instance_type: windows_x2
    max_build_duration: 1
    environment:
      groups:
        - choco
    scripts:
      - name: Create target directory
        script: mkdir out

      - name: Pack
        script: choco pack --out out

      - name: Publish package
        script: choco push out/dcm.1.19.0.nupkg --source https://push.chocolatey.org/ --apikey $env:CHOCO_KEY

    artifacts:
      - out/**
