workflows:
  compile:
    instance_type: windows_x2
    max_build_duration: 10
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Create target directory
        script: mkdir out

      - name: Pack
        script: choco pack --out out

    artifacts:
      - out/**
